# Generated by Django 5.1.7 on 2025-04-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flower", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="tags",
            field=models.ManyToManyField(to="flower.tag"),
        ),
    ]
