# Generated by Django 5.1.7 on 2025-04-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flower", "0002_flower_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="flowers/"),
        ),
    ]
